fileConfigs:
  01_sources.conf: |-
    <source>
      @type dummy
      tag dummy
      rate 50
      dummy [
        {"timestamp": "2025-03-25T21:44:11.502571", "level": "INFO", "mdai_service": "inventory-service", "action": "login", "message": "Action signup processed successfully", "user_id": 2887, "transaction_id": 474027, "duration": 72, "status": "success"},

        {"timestamp": "2025-03-25T21:56:11.502593", "level": "DEBUG", "mdai_service": "inventory-service", "action": "login", "message": "Action inventory-check processed successfully", "user_id": 6538, "transaction_id": 503662, "duration": 188, "status": "failure"},

        {"timestamp": "2025-03-25T22:26:11.502601", "level": "ERROR", "mdai_service": "payment-service", "action": "logout", "message": "Action logout processed successfully", "user_id": 4255, "transaction_id": 436167, "duration": 137, "status": "failure"},

        {"timestamp": "2025-03-25T21:43:11.502609", "level": "WARN", "mdai_service": "user-service", "action": "payment", "message": "Action login processed successfully", "user_id": 5466, "transaction_id": 446064, "duration": 115, "status": "success"},

        {"timestamp": "2025-03-25T21:53:11.502615", "level": "INFO", "mdai_service": "user-service", "action": "inventory-check", "message": "Action inventory-check processed successfully", "user_id": 6363, "transaction_id": 890785, "duration": 59, "status": "success"}


        {"timestamp": "2025-03-25T21:53:11.502615", "level": "INFO", "mdai_service": "important-service", "action": "inventory-check", "message": "Action inventory-check processed successfully", "user_id": 6363, "transaction_id": 890785, "duration": 59, "status": "success"}


        {"timestamp": "2025-03-25T21:53:11.502615", "level": "INFO", "mdai_service": "important-service", "action": "inventory-check", "message": "Action inventory-check processed successfully", "user_id": 6363, "transaction_id": 890785, "duration": 59, "status": "success"}


        {"timestamp": "2025-03-25T21:53:11.502615", "level": "INFO", "mdai_service": "important-service", "action": "inventory-check", "message": "Action inventory-check processed successfully", "user_id": 6363, "transaction_id": 890785, "duration": 59, "status": "success"}


        {"timestamp": "2025-03-25T21:53:11.502615", "level": "INFO", "mdai_service": "important-service", "action": "inventory-check", "message": "Action inventory-check processed successfully", "user_id": 6363, "transaction_id": 890785, "duration": 59, "status": "success"}
      ]
    </source>
    <match dummy>
      @type copy
      <store>
        @type stdout
      </store>
      <store>
        @type forward
        <server>
          host gateway-collector.mdai.svc.cluster.local
          port 8006
        </server>
        <buffer>
          @type memory
          chunk_limit_size 1m
          flush_interval 15s
          retry_max_times 3
        </buffer>
      </store>
    </match>

  02_filters.conf: ""

  03_dispatch.conf: ""

  04_outputs.conf: ""

fluentd:
  resources:
    limits:
      memory: 200Mi
      cpu: 100m
    requests:
      memory: 100Mi
      cpu: 50m

  # Mount the necessary directories to access pod logs
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log
